project:
  type: website
  output-dir: docs

website:
  title: "Emily Marple <3"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - href: field-notes.qmd
        text: Field Notes



format:
  html:
    theme:
      - pulse
      - brand
    css: styles.css
    toc: true
    page-layout: full



